import { PageIntro, SiteShell } from "../site-shell";

export const metadata = { title: "Privacy & Consent | Serene Home Care Services", description: "How Serene’s website enquiries, consent choices and care-related information should be handled." };

export default function PrivacyPage() {
  return (
    <SiteShell><main id="main-content"><PageIntro eyebrow="Privacy and consent" title="Share only what is necessary for the next step" description="This notice explains the current website experience. Serene should obtain legal review and add its formal data-controller details before public launch." /><section className="section"><article className="container policy-content"><p className="policy-date">Draft website notice · reviewed 18 August 2026</p><h2>1. Information collected on this website</h2><p>The assessment form asks for a name, telephone number, broad care need and preferred reply method. Careers and referral forms request only introductory contact and role information. Do not enter diagnoses, medical records, identity documents, financial information or other confidential records in these forms.</p><h2>2. How form information is sent</h2><p>Submitting a form prepares a message and opens WhatsApp. The message is sent only if you choose to continue in WhatsApp. WhatsApp’s own terms and privacy practices apply to that communication.</p><h2>3. Why Serene uses the information</h2><p>The information is used to respond to the enquiry, identify an appropriate next step, arrange an assessment where requested and maintain a basic record of the conversation. Serene should not use health information or photographs for marketing without separate, informed consent.</p><h2>4. Consent and family communication</h2><p>The person receiving care should be involved in decisions wherever possible. Family updates, referrals and information sharing should follow the client’s consent, legal authority and safety obligations. Consent can be limited or withdrawn, although some records may need to be retained where law or safe-care duties require it.</p><h2>5. Accessibility preferences</h2><p>The site can store text-size, contrast and reduced-motion preferences in the browser on your device. These settings are not used to identify you.</p><h2>6. Records, access and correction</h2><p>Serene should document a retention schedule, access controls, incident process and method for people to request access, correction or deletion where applicable. Until a dedicated privacy contact is published, start through 0703 862 025 and ask for the person responsible for privacy.</p><h2>7. Required details before launch</h2><p>Add the verified legal entity name, registration details, physical and postal address, privacy contact, data-retention periods, approved service providers and any cross-border processing information. This draft is operational guidance, not legal advice.</p></article></section></main></SiteShell>
  );
}
