import { PageIntro, SiteShell } from "../site-shell";
import { pageMetadata } from "../seo";

export const metadata = pageMetadata({ title: "Privacy & Consent | Serene Home Care Services", description: "How Serene’s website enquiries, consent choices and care-related information should be handled.", path: "/privacy" });

export default function PrivacyPage() {
  return (
    <SiteShell><main id="main-content"><PageIntro eyebrow="Privacy and consent" title="Share only what is necessary for the next step" description="This notice explains the website enquiry forms, how information is sent and how to contact Serene about privacy." /><section className="section"><article className="container policy-content"><h2>1. Information collected on this website</h2><p>The assessment form asks for a name, telephone number, broad care need and preferred reply method. Careers and referral forms request only introductory contact and role information. Do not enter diagnoses, medical records, identity documents, financial information or other confidential records in these forms.</p><h2>2. How form information is sent</h2><p>Selecting WhatsApp prepares an enquiry message and opens WhatsApp; the message is sent only if you continue there. Selecting phone call opens your device’s calling function, and you share the relevant details during the call. WhatsApp’s own terms and privacy practices apply when that option is used.</p><h2>3. Why Serene uses the information</h2><p>The information is used to respond to the enquiry, identify an appropriate next step, arrange an assessment where requested and maintain a basic record of the conversation.</p><h2>4. Consent and family communication</h2><p>The person receiving care should be involved in decisions wherever possible. Family updates, referrals and information sharing should follow the client’s consent, legal authority and safety obligations. Consent can be limited or withdrawn, although some records may need to be retained where law or safe-care duties require it.</p><h2>5. Accessibility preferences</h2><p>The site can store text-size, contrast and reduced-motion preferences in the browser on your device. These settings are not used to identify you.</p><h2>6. Records, access and correction</h2><p>For questions about records, or to request access, correction or deletion of your information, call 0703 862 025 and ask for the person responsible for privacy.</p></article></section></main></SiteShell>
  );
}
